experiments_dir: ./experiments
log_level: INFO
random_seed: 1

# choose from: predict, train
mode: predict

# If mode is 'predict', specify the model name,
# e.g. /path/to/model/weights.epoch5
model_fn: /home/ruchao/workdir/CS269_project/cs269-nlg-e2e-project/experiments/e2e_model_MLP_seed1-emb256-hid512-drop0.0-bs16-lr0.1_2020-Nov-09_20:55:57/weights.epoch1

# Model module names
data-module: components.data.e2e_data_MLP
model-module: components.model.e2e_model_MLP
training-module: components.trainer.e2e_trainer_MLP
evaluation-module: components.evaluator.e2e_evaluator

data_params:

  train_data: 
  dev_data: 
  test_data: e2e-dataset/testset.csv # specify the file to make preictions on
  vocab_path: e2e-dataset/vocab.txt

  max_src_len: 100
  max_tgt_len: 100

model_params:

  embedding_dim: 256
  embedding_dropout: 0.1
  teacher_forcing_ratio: 1.0

  encoder_params:
    input_size: 256 # NOTE: should be equal to embedding_dim
    hidden_size: 512
    dropout: 0.0

  decoder_params:
    input_size: 512
    hidden_size: 512
    dropout: 0.0

training_params:
  evaluate_prediction: True
  save_model_each_epoch: True
  n_epochs: 30
  batch_size: 16
  optimizer: SGD
  learning_rate: 0.1
