experiments_dir: ./exp2
log_level: INFO
random_seed: 1

# choose from: predict, train
mode: predict

# If mode is 'predict', specify the model name,
# e.g. /path/to/model/weights.epoch5
model_fn: exp2/e2e_model_tfenc_seed1-emb256-hid256-drop0.1-bs32-lr0.0002_2020-Nov-13_20:23:36/weights.epoch2

# Model module names
data-module: components.data.e2e_data_MLP
model-module: components.model.e2e_model_tfenc
training-module: components.trainer.e2e_trainer_MLP
evaluation-module: components.evaluator.e2e_evaluator

data_params:

  train_data: 
  dev_data: 
  test_data: e2e-dataset/testset.csv # specify the file to make preictions on
  vocab_path: e2e-dataset/UKP_vocab.txt

  max_src_len: 50
  max_tgt_len: 100

model_params:
  hit_input: False

  embedding_dim: 256
  embedding_dropout: 0
  teacher_forcing_ratio: 1.0

  encoder_params:
    input_size: 256 # NOTE: should be equal to embedding_dim
    hidden_size: 256
    num_layers: 4
    dropout: 0.0
    n_head: 4
    d_ff: 512
    bidirectional: True

  decoder_params:
    input_size: 512
    hidden_size: 512
    num_layers: 1
    dropout: 0.0

training_params:
  evaluate_prediction: True
  save_model_each_epoch: True
  n_epochs: 15
  batch_size: 32
  optimizer: Adam
  learning_rate: 0.0002
